// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetActivityLogs() {
  return window['go']['main']['App']['GetActivityLogs']();
}

export function GetGostDebugInfo() {
  return window['go']['main']['App']['GetGostDebugInfo']();
}

export function GetGostVersion() {
  return window['go']['main']['App']['GetGostVersion']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRecentActivityLogs(arg1) {
  return window['go']['main']['App']['GetRecentActivityLogs'](arg1);
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function IsGostAvailable() {
  return window['go']['main']['App']['IsGostAvailable']();
}

export function StartProfile(arg1) {
  return window['go']['main']['App']['StartProfile'](arg1);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
