// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {api} from '../models';

export function AddProfile(arg1:database.Profile):Promise<number>;

export function ClearLogs():Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function GetActivityLogs():Promise<Array<database.ActivityLog>>;

export function GetGostDebugInfo():Promise<Record<string, any>>;

export function GetGostVersion():Promise<string>;

export function GetLogs():Promise<Array<api.LogEntry>>;

export function GetProfile(arg1:number):Promise<database.Profile>;

export function GetProfiles():Promise<Array<database.Profile>>;

export function GetRecentActivityLogs(arg1:number):Promise<Array<database.ActivityLog>>;

export function GetRecentLogs(arg1:number):Promise<Array<api.LogEntry>>;

export function IsGostAvailable():Promise<boolean>;

export function StartProfile(arg1:number):Promise<void>;

export function StopProfile(arg1:number):Promise<void>;

export function UpdateProfile(arg1:database.Profile):Promise<void>;
